PYTHON-3679 Support mypy 1.2
PYTHON-3679 Fix Unused "type: ignore" comment

PYTHON-3679 Fix bson/decimal128.py:103: error: Unsupported operand types for + ("Literal['n']"

PYTHON-3679 Ignore bson/son.py:69: error: Value of type variable "Self" of "__new__" of "dict" cannot be "SON[_Key, _Value]"  [type-var]

PYTHON-3679 More fixes

PYTHON-3679 Change cast to type: ignore

PYTHON-3679 Remove unused import